version: '2.1'
services:
  app:
    build: ./.docker
    container_name: openvpn-as
    ports:
      - "8080:8080"
      - "1194:1194/udp"
      - 172.17.0.1:943:943
      - 172.17.0.1:945:945
    cap_add:
      - NET_ADMIN
    # Mount volume 
    volumes:
      - "./data:/app"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./db:/var/lib/mysql
