version: '2.8'
services:
  app:
    build: ./.docker
    container_name: openvpn-as
    ports:
      - 8080:8080
      - 1194:1194/udp
      - 943:943
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # Mount volume 
    volumes:
      - "./data/etc:/app/etc"
      - "./data/log:/app/log"
    restart: unless-stopped
