#!/usr/bin/bash

DIR=/app/lib/python


#while true; do
#    read -p 'Number of concurrent connections: '
#
#    if ! [[ "$REPLY" =~ ^-?[0-9]+$ ]]; then echo 'Error: Not an integer' >&2
#    elif (( REPLY <= 0   ));           then echo 'Error: Need positive integers >0' >&2
#    else
#        CONCURRENT_CONNECTIONS=$REPLY
#        break
#    fi
#done

CONCURRENT_CONNECTIONS=${ALLOWED_CONNECTIONS:=2048}
cd $DIR

PYOVPN=$(ls -1 | grep pyovpn*.egg | grep -v .bak)

#Check for the pyovpn*.egg
if [ ! $PYOVPN ]; then
    echo "PYOVPN does not exist at $(pwd) folder. Script does not support this version of Access Server"
    exit
fi

# Prepare environment
ADDED_PACKAGES=""
if ! [ -x "$(command -v unzip)" ]; then
  ADDED_PACKAGES="$ADDED_PACKAGES unzip"
fi

if ! [ -x "$(command -v zip)" ]; then
  ADDED_PACKAGES="$ADDED_PACKAGES zip"
fi

if ! [ -x "$(command -v pip3)" ]; then
  ADDED_PACKAGES="$ADDED_PACKAGES python3-pip"
fi

if [ ! -z "$ADDED_PACKAGES" ]; then
    echo "Installing necessary packages: $ADDED_PACKAGES"
    apt-get update > /dev/null
    apt-get install -y $ADDED_PACKAGES > /dev/null
fi

pip3 install uncompyle6 > /dev/null

#Extract compiled file
echo "Decompile the library"
mkdir -p unlock
cp $PYOVPN unlock/$PYOVPN

cd $DIR/unlock
unzip -oq $PYOVPN

cd $DIR/unlock/pyovpn/lic/
#Decompile
uncompyle6 uprop.pyc > uprop.py
#Inject code
sed -i "/ret\['concurrent_connections'\] = [0-9]*$/d" uprop.py
sed -i "s/^\([[:space:]]*\)return[[:space:]]*return/\1return/" uprop.py
sed -i "s/^\([[:space:]]*\)return ret/\1ret['concurrent_connections'] = $CONCURRENT_CONNECTIONS\n\1return ret/" uprop.py
rm -f uprop.pyc
#Compile
python3 -O -m compileall uprop.py && mv __pycache__/uprop* uprop.pyc

cd $DIR/unlock
zip -u $PYOVPN pyovpn/lic/uprop.pyc

#cp $PYOVPN /app/etc
mv $PYOVPN ../$PYOVPN

cd $DIR/
rm -rf __pycache__/* $DIR/unlock 

echo "Cleaning"
pip3 uninstall -y uncompyle6 > /dev/null
apt-get remove -y $ADDED_PACKAGES > /dev/null
rm -rf /var/lib/apt/lists/* > /dev/null


echo "Activated successfully."
#echo "The modified license file save to configuration folder /app/etc/$PYOVPN"
echo "Restart the OpenVPNAS service or docker to take effect"
