#!/usr/bin/bash

DIR=/app/lib/python

while true; do
    read -p 'Number of concurrent connections: '

    if ! [[ "$REPLY" =~ ^-?[0-9]+$ ]]; then echo 'Error: Not an integer' >&2
    elif (( REPLY <= 0   ));           then echo 'Error: Need positive integers >0' >&2
    else
        CONCURRENT_CONNECTIONS=$REPLY
        break
    fi
done

cd $DIR

PYOVPN=$(ls -1 | grep pyovpn*.egg | grep -v .bak)

#Check for the pyovpn*.egg
if [ ! $PYOVPN ]; then
    echo "PYOVPN does not exist at $(pwd) folder. Script does not support this version of Access Server"
    exit
fi

# Prepare environment
ADDED_PACKAGES=""
if ! [ -x "$(command -v unzip)" ]; then
  ADDED_PACKAGES="$ADDED_PACKAGES unzip"
fi

if ! [ -x "$(command -v zip)" ]; then
  ADDED_PACKAGES="$ADDED_PACKAGES zip"
fi

if ! [ -x "$(command -v pip3)" ]; then
  ADDED_PACKAGES="$ADDED_PACKAGES python3-pip"
fi

if [ ! -z "$ADDED_PACKAGES" ]; then
    echo "Install packages: $ADDED_PACKAGES"
    apt update > /dev/null
    apt install -y $ADDED_PACKAGES > /dev/null
fi

#Extract code of compiled file
echo "Decompile the library"
mkdir -p unlock
cp $PYOVPN $PYOVPN.bak
cp $PYOVPN unlock/$PYOVPN

cd $DIR/unlock
unzip -oq $PYOVPN
rm -rf $PYOVPN
pip3 install uncompyle6
cd $DIR/unlock/pyovpn/lic/
uncompyle6 uprop.pyc > uprop.py
sed -i "/ret\['concurrent_connections'\] = [0-9]*$/d" uprop.py
sed -i "s/^\([[:space:]]*\)return ret/\1ret['concurrent_connections'] = $CONCURRENT_CONNECTIONS\n\1return ret/" uprop.py
rm -f uprop.pyc
python3 -O -m compileall uprop.py && mv __pycache__/uprop* uprop.pyc

cd $DIR/unlock
DIRS=$(ls -l | grep "^d" | awk '{print $9}')
zip -qr $PYOVPN.zip $DIRS
mv $PYOVPN.zip ../$PYOVPN

cd $DIR/
rm -rf __pycache__/* $DIR/unlock

echo "Cleaning"
pip3 uninstall -y uncompyle6
apt remove -y $ADDED_PACKAGES
rm -rf /var/lib/apt/lists/*

echo "Activated successfully. Restart the OpenVPNAS service or docker to take effect"
#Follow: https://devopsvn.xyz/2021/07/29/huong-dan-cai-dat-va-unlock-openvpn-access-server/